/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    'case-studies': CaseStudy;
    pages: Page;
    projects: Project;
    heroes: Hero;
    ctas: Cta;
    socials: Social;
    testimonials: Testimonial;
    tools: Tool;
    icons: Icon;
    images: Image;
    users: User;
  };
  globals: {
    about: About;
    nav: Nav;
    'case-study-listing': CaseStudyListing;
    'toolbox-listing': ToolboxListing;
    'testimonial-listing': TestimonialListing;
  };
}
export interface CaseStudy {
  id: string;
  internalTitle?: string;
  title?: string;
  slug?: string;
  excerpt?: string;
  featuredImage?: string | Image;
  intro?: {
    heading?: string;
    text?: {
      [k: string]: unknown;
    }[];
    image?: string | Image;
    cta?: string[] | Cta[];
  };
  caseStudySections?: (
    | {
        image?: string | Image;
        id?: string;
        blockName?: string;
        blockType: 'imageBlock';
      }
    | {
        heading?: string;
        text?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'textBlock';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Image;
    noIndex?: boolean;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Image {
  id: string;
  alt: string;
  base64?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Cta {
  id: string;
  label?: string;
  linkType?: 'internal' | 'external';
  internalLink?: string | Page;
  externalLink?: string;
  fullTitle?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Page {
  id: string;
  title?: string;
  slug?: string;
  pageSections?: (
    | {
        hero?: string | Hero;
        sectionId?: string;
        id?: string;
        blockName?: string;
        blockType: 'heroBlock';
      }
    | {
        singleUse?: 'about' | 'case-study-listing' | 'toolbox-listing' | 'testimonial-listing';
        sectionId?: string;
        id?: string;
        blockName?: string;
        blockType: 'singleUseBlock';
      }
    | {
        socials?: string[] | Social[];
        sectionId?: string;
        id?: string;
        blockName?: string;
        blockType: 'socialsBlock';
      }
  )[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Image;
    noIndex?: boolean;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Hero {
  id: string;
  icon?: string | Icon;
  heading: string;
  headingTag: string;
  coloredSubhead?: {
    [k: string]: unknown;
  }[];
  subhead?: string;
  homepage?: boolean;
  doodles?: boolean;
  cta?: string | Cta;
  updatedAt: string;
  createdAt: string;
}
export interface Icon {
  id: string;
  alt: string;
  base64?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Social {
  id: string;
  icon: string | Icon;
  label: string;
  socialLink?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Project {
  id: string;
  title?: string;
  slug?: string;
  excerpt?: string;
  featuredImage?: string | Image;
  intro?: {
    description?: string;
    image?: string | Image;
    cta?: string[] | Cta[];
  };
  projectSections?: (
    | {
        image?: string | Image;
        id?: string;
        blockName?: string;
        blockType: 'imageBlock';
      }
    | {
        heading?: string;
        text?: {
          [k: string]: unknown;
        }[];
        id?: string;
        blockName?: string;
        blockType: 'textBlock';
      }
  )[];
  caseStudies?: string[] | CaseStudy[];
  meta?: {
    title?: string;
    description?: string;
    image?: string | Image;
    noIndex?: boolean;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Testimonial {
  id: string;
  author: string;
  jobTitle: string;
  company: string;
  linkedin?: string;
  image: string | Image;
  excerpt?: string;
  testimonial: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Tool {
  id: string;
  title: string;
  icon: string | Icon;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface About {
  id: string;
  image?: string | Image;
  title?: string;
  coloredSubhead?: {
    [k: string]: unknown;
  }[];
  text?: {
    [k: string]: unknown;
  }[];
  pets?: {
    harvey?: string | Image;
    athena?: string | Image;
    warren?: string | Image;
    jasper?: string | Image;
  };
  updatedAt?: string;
  createdAt?: string;
}
export interface Nav {
  id: string;
  menuItems?: {
    page?: string | Page;
    overridePageName?: boolean;
    customLabel?: string;
    linkToSection?: boolean;
    sectionId?: string;
    id?: string;
  }[];
  footerCopyrightText?: string;
  updatedAt?: string;
  createdAt?: string;
}
export interface CaseStudyListing {
  id: string;
  title?: string;
  icon?: string | Icon;
  caseStudies?: string[] | Project[];
  updatedAt?: string;
  createdAt?: string;
}
export interface ToolboxListing {
  id: string;
  title?: string;
  icon?: string | Icon;
  description?: string;
  tools?: string[] | Tool[];
  updatedAt?: string;
  createdAt?: string;
}
export interface TestimonialListing {
  id: string;
  title?: string;
  icon?: string | Icon;
  testimonials?: string[] | Testimonial[];
  updatedAt?: string;
  createdAt?: string;
}
