/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    pages: Page;
    heroes: Hero;
    ctas: Cta;
    projects: Project;
    testimonials: Testimonial;
    tools: Tool;
    icons: Icon;
    images: Image;
    users: User;
  };
  globals: {
    nav: Nav;
    'case-study-listing': CaseStudyListing;
    'toolbox-listing': ToolboxListing;
    'testimonial-listing': TestimonialListing;
  };
}
export interface Page {
  id: string;
  title?: string;
  slug?: string;
  sections?: {
    hero?: string | Hero;
    id?: string;
    blockName?: string;
    blockType: 'heroBlock';
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Hero {
  id: string;
  icon?: string | Icon;
  heading: string;
  headingTag: string;
  coloredSubhead?: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Icon {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Cta {
  id: string;
  label?: string;
  linkType?: 'internal' | 'external';
  internalLink?: string | Page;
  externalLink?: string;
  fullTitle?: string;
  updatedAt: string;
  createdAt: string;
}
export interface Project {
  id: string;
  title: string;
  cardInfo?: {
    snippet?: string;
    image?: string | Image;
  };
  intro?: {
    description?: string;
    image?: string | Image;
  };
  updatedAt: string;
  createdAt: string;
}
export interface Image {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Testimonial {
  id: string;
  author: string;
  jobTitle: string;
  company: string;
  linkedin?: string;
  image: string | Image;
  excerpt?: string;
  testimonial: {
    [k: string]: unknown;
  }[];
  updatedAt: string;
  createdAt: string;
}
export interface Tool {
  id: string;
  title: string;
  icon: string | Icon;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean;
  apiKey?: string;
  apiKeyIndex?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Nav {
  id: string;
  menuItems?: {
    page?: string | Page;
    overridePageName?: boolean;
    customLabel?: string;
    id?: string;
  }[];
  footerCopyrightText?: string;
  updatedAt?: string;
  createdAt?: string;
}
export interface CaseStudyListing {
  id: string;
  title?: string;
  icon?: string | Icon;
  updatedAt?: string;
  createdAt?: string;
}
export interface ToolboxListing {
  id: string;
  title?: string;
  icon?: string | Icon;
  tools?: string[] | Tool[];
  updatedAt?: string;
  createdAt?: string;
}
export interface TestimonialListing {
  id: string;
  title?: string;
  icon?: string | Icon;
  updatedAt?: string;
  createdAt?: string;
}
